# Generated by Django 5.2.7 on 2025-10-30 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordtoken",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
