# Generated by Django 5.2.7 on 2025-11-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resetpasswordtoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
    ]
